user_name=input("ENTER YOUR NAME: ")
user_age=input("ENTER YOUR AGE:")
print("welcome "+user_name+  " Gg's "+ user_age  +" years old wow pretty young monad is adoptable keep building.....monad loves you".upper())
colour= input("ENTER ANY COLOUR:")
dapp=input("ENTER YOUR FAVOURITE MONAD DAPP:")
influence=input("ENTER YOUR FAVOURITE MONAD INFLUENCE:")
print("roses are "+ colour)
print(dapp+" is my favourite dapp in monad ecosystem")
print(influence+ " is my favourite influence on monad")
print("I LOVE MONAD")